# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal8825-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a53x,$(TARGET_DEVICE)),)

endif
